### ISSUE TITLE
리팩토링을 한다면

### ISSUE THREAD

**Issue by goldfrosch** [FeelingXD/reservation#8]
DDD 원칙에 맞게 해보는건 어떠한가요

https://velog.io/@jsb100800/Spring-boot-directory-package#-%EB%8F%84%EB%A9%94%EC%9D%B8%ED%98%95-%EB%94%94%EB%A0%89%ED%84%B0%EB%A6%AC-%EA%B5%AC%EC%A1%B0

**Comment by FeelingXD** [comment]
참고 해보도록 하겟읍니다.
